### ISSUE TITLE
Constraint option 'getter' not working outside annotations

### ISSUE THREAD

**Issue by King2500** [barbieswimcrew/zip-code-validator#23]
When using the `ZipCode` constraint not with annotation inside data class but as form option like this:

```php
class ZipCodeFormController extends Controller
{
    public function zipcodeAction(Request $request)
    {
        $address = new Address();

        $builder = $this->createFormBuilder($address);
        $builder->add('country', TextType::class);
        $builder->add('zipcode', TextType::class, [
            'constraints' => [
                new ZipCode(['getter' => 'getCountry'])
            ]
        ]);

        $builder->add('save', SubmitType::class, ['label' => 'Send']);

        $form = $builder->getForm();
        $form->handleRequest($request);

        //...
    }
}

class Address
{
    protected $zipCode;

    protected $country;
//...
    public function getCountry()
    {
        return $this->country;
    }
}
```

... then `$this->context->getObject()` in `ZipCodeValidator` does return null. 

This is also becoming a problem when you don't have a data class but working with form data as array and want a way to get the access to `country` key from the other field.

I'll be posting a PR fixing these problems.

**Comment by barbieswimcrew** [comment]
Sorry for the inconvenience @King2500 but due to some TravisCI issues I was able to detect some issues on your PR recently after merging it. Therefor I had to revert now...

So... first of all you make use of FormInterface in the ZipCodeValidator (line 237) which is NOT defined as a requirement of the package and therefor should not in the future. Could you please solve that?

Furthermore zwo unit tests failed in TravisCI... those are: 
- it_validates_a_zip_code_with_getter_from_form_data
- it_validates_a_zip_code_with_property_path_from_form_data

Would be great if you'd apply solutions for those issues. Thank you in advance!

**Comment by barbieswimcrew** [comment]
Due to no further reactions this issue will be closed. If the issue is still there, please create a new one. Thanks.
