### ISSUE TITLE
Invalid iso code "" for validation

### ISSUE THREAD

**Issue by mikeyudin** [barbieswimcrew/zip-code-validator#4]
When validating a country, if the country dropdown is left blank, a `ConstraintDefinitionException` is thrown, even though there is also a NotBlank/NotNull validator on the country field:

``` php
if (!isset($this->patterns[$iso])) {
        if ($constraint->strict) {
            throw new ConstraintDefinitionException(sprintf('Invalid iso code "%s" for validation', $iso));
        } else {
             return;
        }
```

Should I just set strict to false, or is this a bug?

**Comment by barbieswimcrew** [comment]
Hi Mike, thanks for reporting that issue. I'd say it's both, a bug and even kind of an enhancement. You could use the strict property, that's right. But in fact this is not a solution that looks quite elegant to me. So that's why I was trying to dissolve that in my latest release v1.0.5. So please have a try and let me know if there are any further problems.

**Comment by mikeyudin** [comment]
Great, thank you for fixing it so quickly!  Will test later today, but the commit looks like it's solved.
