### ISSUE TITLE
Validation for country Latvia not work correctly

### ISSUE THREAD

**Issue by lasotaartur** [barbieswimcrew/zip-code-validator#7]
Library don't check prefix letters "LV-", so valid zipcode from list http://rekvizitai.vz.lt/pl/kody-pocztowe/vilnius/2/ is not properly validated.

Source: http://publications.europa.eu/code/en/en-390105.htm

**Comment by barbieswimcrew** [comment]
Sorry but is it the validation for LATVIA [LV] or for LITHUANIA [LT] that will not work properly?

**Comment by lasotaartur** [comment]
I.e. validation for "LT-01001" return false but should return true.

**Comment by barbieswimcrew** [comment]
Hey, sorry for asking again but actually I'm confused. As you wrote in your issues title, the "validation for country **Latvia**"  ain't working. But in your example from yesterday you are explicitly mentioning "**LT**-01001" - so NOT LV for Latvia but LT... which actually is Lithuania... so if you are trying to validate LT-01001 with Latvia regex this will not work at all because the postal code format is not valid to Latvia's postal code definitions. If you are trying to validate LT-01001 with Lithuania regex it might work quite well.

So please let me know if I do misunderstand what you want or if you just mistake Latvia with Lithuania. 

Thank you!

**Comment by barbieswimcrew** [comment]
@lasotaartur Any news regarding this? Please reply to my comment from 23 Nov - otherwise I'm sorry for not being able to solve that issue.

**Comment by barbieswimcrew** [comment]
Sorry but I'm closing this issue now due to not getting any reply.
